basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

user_auth_basic/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('basic_app.urls')),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_url = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfile


class UserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email=email)

        if user.exists():
            raise forms.ValidationError('Email already registered!')

        return email


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('portfolio_url', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect


def index(request):
    return render(request, 'basic_app/index.html')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }
    return render(request, 'basic_app/register.html', context)


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('<h2>User with enter credentials no longer active!</h2>')
        else:
            return HttpResponse('<h2>Please enter correct username and password!</h2>')

        print(username, password)
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'basic_app/login.html')


@login_required
def profile(request):
    return HttpResponse('You are loged in!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponse('You are successfully logged out!')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Basic Authentication</title>
  </head>
  <body>

    <!-- Navbar start -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'index' %}" class="navbar-brand">DjangoAuth</a></li>
              <li><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
              {% if not request.user.is_authenticated %}
                <li><a href="{% url 'basic_app:login' %}" class="nav-link">Login</a></li>
                <li><a href="{% url 'basic_app:register' %}" class="nav-link">Register</a></li>
              {% else %}
                <li><a href="{% url 'basic_app:profile' %}" class="nav-link">Profile</a></li>
                <li><a href="{% url 'basic_app:logout' %}" class="nav-link">Logout</a></li>
              {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Navbar end -->

    <!-- Main body start -->
    <div class="container mt-5">
        {% block body %}
        {% endblock body %}
    </div>
    <!-- Main body end -->

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

templates/basic_app/index.html
{% extends 'base.html' %}

{% block body %}

    <h1 class="text-center alert alert-info">Home Page</h1>

{% endblock body %}

templates/basic_app/login.html
{% extends "base.html" %}

{% block body %}

    <h1 class="text-center alert alert-info">Login Form</h1>

    <form action="" method="POST">
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" class="form-control">

        <label for="password">Password</label>
        <input type="password" name="password" placeholder="********" class="form-control">
        <br>
        <input type="submit" value="Login" class="btn btn-outline-primary">
    </form>

{% endblock body %}

templates/basic_app/register.html
{% extends 'base.html' %}

{% block body %}

    <h1 class="text-center alert alert-info">Registration Page</h1>

    {% if registered %}
        <h1 class="text-center alert alert-success">Thank you for registring!</h1>
    {% else %}
        <form action="" method="POST" enctype="multipart/form-data">
            
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}

            <input type="submit" value="Register" class='btn btn-outline-info'>
            
        </form>
    {% endif %}

{% endblock body %}